version: '0.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - PGDATABASE=${LOCAL_DB_DBNAME}
      - PGUSER=${LOCAL_DB_USER}
      - PGPASSWORD=${LOCAL_DB_PWD}

    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local