version: '0.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER:${LOCAL_DB_USER}
      POSTGRES_PASSWORD:${LOCAL_DB_PWD}
      POSTGRES_DB:${LOCAL_DB_DBNAME}

    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local